#! .travis.yml | @author Brikcss (https://github.com/brikcss) | @reference (https://docs.travis-ci.com/user/customizing-the-build) #

language: node_js
node_js: "9"

cache:
  bundler: true
  npm: true

notifications:
  email:
    on_failure: always

env: NODE_ENV=test

before_script: npm prune -d
script: npm test -d

deploy:
  # Publish to NPM
  - provider: npm
    email: thezimmee@gmail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
  # Release to GitHub
  - provider: releases
    api_key: $GITHUB_TOKEN
    draft: true
    file_glob: true
    file:
      - examples/**/*
      - esm/**/*
      - umd/**/*
      - README.md
      - LICENSE.md
      - CHANGELOG.md
    skip_cleanup: true

# Semantic release to NPM and GitHub.
# deploy:
#   provider: script
#   skip_cleanup: true
#   script:
#     - npx semantic-release

# Publish to NPM only.
branches:
  only:
    - master
    - /^greenkeeper/.*$/
# Semantic release to NPM and GitHub.
# branches:
#   except:
#     - /^v\d+\.\d+\.\d+$/
