#! .travis.yml | @author Brikcss (https://github.com/brikcss) | @reference (https://docs.travis-ci.com/user/customizing-the-build) #

language: node_js
node_js: "9"

cache:
  bundler: true
  # directories:
  #   - node_modules

notifications:
  email:
    on_failure: always

env: NODE_ENV=test

# Publish to NPM only.
before_script: npm prune -d
script:
  - npm test -d
  - npm run release
# Publish to NPM
deploy:
  provider: npm
  email: thezimmee@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true

# deploy:
#   provider: npm
#   email: thezimmee@gmail.com
#   api_key: $NPM_TOKEN
#   skip_cleanup: true
# Semantic release to NPM and GitHub.
# deploy:
#   provider: script
#   skip_cleanup: true
#   script:
#     - npx semantic-release

# Publish to NPM only.
branches:
  only:
    - master
    - /^greenkeeper/.*$/
# Semantic release to NPM and GitHub.
# branches:
#   except:
#     - /^v\d+\.\d+\.\d+$/
